version: '3.8'
services:
    mongodb:
        image : mongo:latest
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./mongodb/database:/data/db
        ports:
            - 27017:27017
  
    my-node-app:
        depends_on:
            - mongodb
        image : dr34m3r/node-app-rest:latest
        build: .
        container_name: my-node-app
        environment:
            NODE_ENV: production
        ports:
            - "3000:3000"
        volumes:
            - .:/app

